---
- hosts: bkend_dev
  remote_user: ubuntu
  gather_facts: false
  tasks:
  - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
      become: true
  
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:openjdk-r/ppa'

  - name: Install Oracle Java 8
    become: yes
    apt: 
      name: ['openjdk-8-jdk'] 
      state: latest

  - name: Run simple command
    shell: java -version
    register: console

  - debug: msg="{{ console.stderr }}"
