---
- hosts: dev
  remote_user: ubuntu
  tasks:
  - name: Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:openjdk-r/ppa'

  - name: Install Oracle Java 8
    become: yes
    apt: 
      name: ['openjdk-8-jdk'] 
      state: latest

  - name: Run simple command
    shell: java -version
    register: console

  - debug: msg="{{ console.stderr }}"
